version: "3.8"
services:
  db:
    image: postgres:15-alpine
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    networks:
      - backend_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue_frontend
    ports:
      - "3000:3000"
    networks:
      - frontend_network
    depends_on:
      - backend_central
    environment:
      VUE_APP_API_URL: "http://localhost:8080"  # Aquí puedes configurar la URL del backend

  backend_central:
    build:
      context: ./Go-Backend
      dockerfile: Dockerfile
    container_name: go_backend_central
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: mydatabase
    ports:
      - "8080:8080"
    networks:
      - backend_network

volumes:
  postgres_data:

networks:
  backend_network:
    driver: bridge
  frontend_network:
    driver: bridge
